name: Go Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.26

      - name: Build binaries
        run: |
          OUTPUT="silo-${{ matrix.os }}-${{ matrix.arch }}"
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            OUTPUT="${OUTPUT}.exe"
          fi
          echo "Building $OUTPUT with version $TAG"
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X 'github.com/nxrmqlly/silo/internal/cli.Version=${TAG}'" -o "$OUTPUT" ./cmd/silo
          ls -lh "$OUTPUT"

      - uses: softprops/action-gh-release@v2
        with:
          files: silo-${{ matrix.os }}-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}